# Generated by Django 2.1.5 on 2019-02-12 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bloqueio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Conversa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.CharField(max_length=500)),
                ('hora_envio', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='mensagemimagem')),
                ('like', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Convite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Justificativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justificativa', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotoperfil/')),
                ('nome', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=20)),
                ('nome_empresa', models.CharField(max_length=255)),
                ('ativo', models.BooleanField(default=True)),
                ('contatos', models.ManyToManyField(related_name='_perfil_contatos_+', to='perfil.Perfil')),
                ('contatos_bloqueados', models.ManyToManyField(related_name='meus_contatos_bloqueados', through='perfil.Bloqueio', to='perfil.Perfil')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='justificativa',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfil.Perfil'),
        ),
        migrations.AddField(
            model_name='convite',
            name='convidado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convites_recebidos', to='perfil.Perfil'),
        ),
        migrations.AddField(
            model_name='convite',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convites_feitos', to='perfil.Perfil'),
        ),
        migrations.AddField(
            model_name='conversa',
            name='receptor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_recebidas', to='perfil.Perfil'),
        ),
        migrations.AddField(
            model_name='conversa',
            name='remetente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_enviadas', to='perfil.Perfil'),
        ),
        migrations.AddField(
            model_name='bloqueio',
            name='perfil_bloqueado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueado', to='perfil.Perfil'),
        ),
        migrations.AddField(
            model_name='bloqueio',
            name='perfil_bloqueador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueador', to='perfil.Perfil'),
        ),
    ]
