# Generated by Django 2.1.4 on 2019-01-03 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_remove_postagem_author'),
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='postagem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='post.Postagem'),
        ),
    ]
