# Generated by Django 2.1.4 on 2019-01-07 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0003_remove_perfil_postagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='bloqueado',
            field=models.BooleanField(default=False),
        ),
    ]
