# Generated by Django 2.1.4 on 2019-01-08 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0004_perfil_bloqueado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bloqueio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='bloqueado',
        ),
        migrations.AddField(
            model_name='perfil',
            name='bloqueados',
            field=models.ManyToManyField(related_name='_perfil_bloqueados_+', to='perfil.Perfil'),
        ),
        migrations.AddField(
            model_name='bloqueio',
            name='bloqueado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueio_recebidos', to='perfil.Perfil'),
        ),
        migrations.AddField(
            model_name='bloqueio',
            name='bloqueador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfis_bloqueados', to='perfil.Perfil'),
        ),
    ]
