# Generated by Django 2.1.4 on 2019-01-08 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0005_auto_20190107_2335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloqueio',
            name='bloqueado',
        ),
        migrations.RemoveField(
            model_name='bloqueio',
            name='bloqueador',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='bloqueados',
        ),
        migrations.DeleteModel(
            name='Bloqueio',
        ),
    ]
