# Generated by Django 2.1.5 on 2019-01-19 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0009_auto_20190117_2231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='justificativa',
            old_name='justificativa',
            new_name='texto',
        ),
    ]
