# Generated by Django 2.1.5 on 2019-01-19 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0010_auto_20190119_1406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='justificativa',
            old_name='texto',
            new_name='justificativa',
        ),
    ]
