# Generated by Django 2.1.5 on 2019-01-28 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0014_auto_20190127_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(blank=True, default='fotoperfil/the_punisher_minimal_logo_4k-1366x768.jpg', null=True, upload_to='fotoperfil/'),
        ),
    ]
