# Generated by Django 2.0.6 on 2019-02-12 04:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('published_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='postagemimagem')),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='perfil.Perfil')),
            ],
        ),
    ]
