# Generated by Django 2.1.4 on 2019-01-03 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagem',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='perfil.Perfil'),
        ),
    ]
