# Generated by Django 2.1.4 on 2019-01-08 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_postagem_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postagem',
            name='title',
        ),
    ]
