# Generated by Django 2.1.5 on 2019-01-27 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_postagem_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postagem',
            name='imagem',
        ),
    ]
